POST  http://{{host}}/admin/fail
X-MBX-APIKEY: vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A
Content-Type: application/json


 {
     "symbol": "BTCUSDT",
     "endpoint": "leverage",
     "payload": {
       "msg": "Dummy message",
       "code": "-123"
     }
 }

> {%
client.global.set("id", response.body["id"]);
%}

###

GET  http://{{host}}/admin/fail?endpoint=order
X-MBX-APIKEY: vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A
###

GET  http://{{host}}/admin/fail/{{id}}
X-MBX-APIKEY: vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A
###

PUT  http://{{host}}/admin/fail/{{id}}
X-MBX-APIKEY: vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A
Content-Type: application/json


 {
     "symbol": "BTC",
     "payload": {
       "msg": "Updated Dummy message",
       "code": "-123"
     }
 }

###

DELETE  http://{{host}}/admin/fail/{{id}}
X-MBX-APIKEY: vmPUZE6mv9SD5VNHk4HlWFsOr6aKE2zvsw0MuIgwCIPy6utIco14y7Ju91duEh8A
###