CREATE TABLE IF NOT EXISTS FAIL
(
    ID        BIGSERIAL,
    SYMBOL    VARCHAR(255),
    ENDPOINT  VARCHAR(255),
    PAYLOAD   TEXT,
    API_KEY   VARCHAR(255),
    IS_ACTIVE BOOLEAN,
    UNIQUE (ID)
)
