CREATE TABLE IF NOT EXISTS TRANSACTION
(
    ID          BIGSERIAL,
    SYMBOL      VARCHAR(255),
    INCOME_TYPE VARCHAR(255),
    INCOME      VARCHAR(255),
    ASSET       VARCHAR(255),
    INFO        VARCHAR(255),
    TRAN_ID     VARCHAR(255),
    TRADE_ID    VARCHAR(255),
    API_KEY     VARCHAR(255),
    TIME        TIMESTAMP,
    UNIQUE (ID)
)
